security:
  oauth2:
    google:
      client:
        clientId: 731251325623-959g3pe5e5s8r82hasvjgdceg884t4vt.apps.googleusercontent.com
        clientSecret: yQlL2apLSbxHYePJllEpfpjd
        accessTokenUri: https://accounts.google.com/o/oauth2/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        scope: email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me